### PR TITLE
space traveler hub working

### PR DESCRIPTION
**Pull request by EvansSnave**
-implemented react-redux
-Implemented redux toolkit
-Missions and rockets retrieved from API
-Style similar to the given design.
-Reserve and cancel reservation rocket
-Join and leave missions
-dragon section working

### CODE REVIEW

**Review by Olamarx — CHANGES_REQUESTED** [review]
Hi Team,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has only contributions from two partners, whereas you are three on this team, I will encourage you to make sure your third partner also join in the project development.

Also, I noticed you guys did not review each other's projects, I will encourage you to review each other's projects and make sure you submit from dev branch into main branch since the review you will be making would follow the gitflow.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by addod19** [comment]
## Hi TEAM, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is invalid because you have submitted the wrong project for review. Kindly pay attention to the submission you make for the project submission

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by skyv26 — COMMENTED** [review]
## Hi @EvansSnave , @addod19 , @gdvl777  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🟨 



## Reason 🗒️ 
You have submitted a project with an old PR, you need to create a brand new repository and first set the Kanban board successfully with equal task distribution. After that make sure you all are working together and have at least an equal number of commits on the project to ensure that you are working as a pair-programmer. Then after all this, you create a new PR for the project review. You still have a good amount of time, so that's why we (CRs) believe that you will do it. Best of luck for the project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

#### Cheers, and Happy coding!👏👏👏

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   @skyv26
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   linkedin-skyv2022
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   @vrma_aakash
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   @skybrel
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   @skybrel
</a>

</td>
</tr>
</table>

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by nicupop729 — COMMENTED** [review]
Hello team 👋,

This is a manual review.

Please note that during pair programming activities, we cannot utilize previously approved old repositories.
Let's make the most of our group project and collaborate to develop this fantastic project.
Please create a completely new repository and work on it as a team. Each of you should create the rockets, missions, and dragons sections accordingly.
Ensure that the tasks are evenly divided among you using the Kanban board.

Best of luck with your new project! 🍀

Keep rocking 🚀!

**Pull request closed without merging**
